### PR TITLE
Added MVC architechture with modules 

### PR DESCRIPTION
**Pull request by GauravSingh9356**
I have added some modules and cleanly differentiated server.js and app.js files following MVC architecture. Plss provide your backend implementation views/ideas so that I can start on building models, routers, and controllers.

Till now #20 is solved.

### CODE REVIEW

**Comment by himanshujaidka** [comment]
give me some time to check the code

**Comment by Sureshshukla78** [comment]
wrong, missing all the folder structure that's required for following mvc pattern.
Please assign this issue to me.

**Comment by GauravSingh9356** [comment]
@Sureshshukla78 bro I have not added routers, controllers, and models as backend architecture are not clear. I didn't want to add unnecessary files without knowing the flow. As of now, the modules which I was sure will be used have been added by me.

**Comment by Sureshshukla78** [comment]
ok bro you have mentioned to setup complete mvc pattern that's why i have commented but ok you can go as you want.

**Pull request merged**
